const { auth: adminAuth, db } = require('../config/firebase');
const jwt = require('jsonwebtoken');

// Check if app is in maintenance mode
const checkMaintenanceMode = async () => {
    try {
        const settingsDoc = await db.collection('appSettings').doc('global').get();
        if (settingsDoc.exists) {
            return settingsDoc.data().maintenanceMode === true;
        }
    } catch (error) {
        console.error('Error checking maintenance mode:', error);
    }
    return false;
};

/**
 * User Authentication middleware
 * Verifies Firebase ID token and attaches user to request
 */
const auth = async (req, res, next) => {
    try {
        const authHeader = req.header('Authorization');

        if (!authHeader || !authHeader.startsWith('Bearer ')) {
            return res.status(401).json({
                success: false,
                message: 'Access denied. No token provided.'
            });
        }

        const token = authHeader.replace('Bearer ', '');

        try {
            // Verify Firebase ID token
            const decodedToken = await adminAuth.verifyIdToken(token);
            const userId = decodedToken.uid;

            // Fetch user from Firestore
            const userRef = db.collection('users').doc(userId);
            const userSnap = await userRef.get();

            if (!userSnap.exists) {
                return res.status(401).json({
                    success: false,
                    message: 'User account not found in database.'
                });
            }

            const userData = { id: userSnap.id, ...userSnap.data() };

            // Check if user is banned
            if (userData.isBanned) {
                return res.status(403).json({
                    success: false,
                    message: `Your account is banned. Reason: ${userData.banReason || 'Violation of terms'}`
                });
            }

            // Check maintenance mode (admins bypass)
            if (userData.role !== 'admin') {
                const isMaintenanceMode = await checkMaintenanceMode();
                if (isMaintenanceMode) {
                    return res.status(503).json({
                        success: false,
                        message: 'The platform is currently under maintenance. Please try again later.',
                        maintenanceMode: true
                    });
                }
            }

            req.user = userData;
            req.userId = userId;
            next();
        } catch (firebaseError) {
            console.error('Firebase verify error:', firebaseError.message);
            return res.status(401).json({
                success: false,
                message: 'Invalid or expired token.'
            });
        }
    } catch (error) {
        console.error('Auth middleware error:', error);
        res.status(500).json({
            success: false,
            message: 'Authentication error.'
        });
    }
};

/**
 * Admin Authentication middleware
 * Verifies custom JWT generated by adminLogin
 */
const isAdmin = async (req, res, next) => {
    try {
        const authHeader = req.header('Authorization');

        if (!authHeader || !authHeader.startsWith('Bearer ')) {
            return res.status(401).json({
                success: false,
                message: 'Admin access denied. No token provided.'
            });
        }

        const token = authHeader.replace('Bearer ', '');

        try {
            const decoded = jwt.verify(
                token,
                process.env.JWT_SECRET || 'reelbox-admin-secret-key-2024'
            );

            if (decoded.role !== 'admin') {
                return res.status(403).json({
                    success: false,
                    message: 'Insufficient permissions. Admin only.'
                });
            }

            req.admin = decoded;
            next();
        } catch (jwtError) {
            console.error('JWT verify error:', jwtError.message);
            return res.status(401).json({
                success: false,
                message: 'Invalid or expired admin session. Please login again.'
            });
        }
    } catch (error) {
        console.error('Admin Auth middleware error:', error);
        res.status(500).json({
            success: false,
            message: 'Internal server error during authentication.'
        });
    }
};

/**
 * Optional auth middleware
 */
const optionalAuth = async (req, res, next) => {
    try {
        const authHeader = req.header('Authorization');

        if (authHeader && authHeader.startsWith('Bearer ')) {
            const token = authHeader.replace('Bearer ', '');

            try {
                const decodedToken = await adminAuth.verifyIdToken(token);
                req.userId = decodedToken.uid;
                const userSnap = await db.collection('users').doc(req.userId).get();
                if (userSnap.exists) {
                    req.user = { id: userSnap.id, ...userSnap.data() };
                }
            } catch (firebaseError) {
                // Ignore invalid tokens for optional auth
            }
        }
        next();
    } catch (error) {
        next();
    }
};

/**
 * Skip Auth middleware (Bypass for development)
 */
const skipAuth = (req, res, next) => {
    req.user = { id: 'admin_bypass_id', role: 'admin', name: 'Admin Bypass' };
    req.userId = 'admin_bypass_id';
    next();
};

module.exports = { auth, isAdmin, optionalAuth, skipAuth };

